version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Demon
      POSTGRES_DB: srknotesapp-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: SRKNote
    environment:
      - DOTENV=.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data: