"""
logger.py
----------
Logging module for SRKNote.

This module sets up a file-based logger and provides middleware
to log all incoming HTTP requests and their responses. Sensitive
data in requests (like passwords or tokens) is masked before logging
to maintain security compliance.
"""

import logging
import time
import json
from pathlib import Path
from fastapi import Request, Response


def setup_logger() -> logging.Logger:
    """
    Configure and return a logger for SRKNote API events.

    - Creates a 'logs' directory if it doesn't exist.
    - Writes logs to 'logs/log.log'.
    - Sets log format with timestamp, level, and message.
    - Prevents duplicate handlers if logger is already initialized.

    Returns:
        logging.Logger: Configured logger instance.
    """
    log_dir = Path("logs")
    log_dir.mkdir(exist_ok=True)

    log_file = log_dir / "log.log"

    loger = logging.getLogger("api_logger")
    loger.setLevel(logging.INFO)

    if not loger.handlers:
        handler = logging.FileHandler(log_file)
        handler.setFormatter(
            logging.Formatter('%(asctime)s | %(levelname)s | %(message)s')
        )
        loger.addHandler(handler)

    return loger


# Global logger instance for use across SRKNote
logger = setup_logger()


def mask_sensitive_data(data: dict) -> dict:
    """
    Mask sensitive fields in a dictionary before logging.

    Sensitive fields include: password, token, secret, api_key.

    Args:
        data (dict): Dictionary containing request or response data.

    Returns:
        dict: Copy of the dictionary with sensitive values masked.
    """
    sensitive = {"password", "token", "secret", "api_key"}

    if isinstance(data, dict):
        return {
            k: "***MASKED***" if k.lower() in sensitive else v
            for k, v in data.items()
        }
    return data


async def log_requests(request: Request, call_next):
    """
    FastAPI middleware to log incoming HTTP requests and outgoing responses.

    Logs:
    - Request method, URL, query parameters, and masked body (for POST/PUT/PATCH)
    - Response status code and processing time
    - Errors with stack trace if request handling fails

    Args:
        request (Request): Incoming FastAPI request object.
        call_next: Function to execute the next middleware or route handler.

    Returns:
        Response: The response generated by the route handler.
    """
    request_id = id(request)
    start_time = time.time()

    # Log basic request info
    log_msg = f"[{request_id}] {request.method} {request.url.path}"

    if request.query_params:
        log_msg += f" | Query: {dict(request.query_params)}"

    # Log request body for POST, PUT, PATCH methods
    if request.method in ["POST", "PUT", "PATCH"]:
        try:
            body = await request.body()
            if body:
                body_json = json.loads(body.decode())
                body_json = mask_sensitive_data(body_json)
                log_msg += f" | Body: {json.dumps(body_json)}"
        except Exception:
            pass  # Ignore errors parsing body

    logger.info(log_msg)

    try:
        # Execute the next middleware/route handler
        response = await call_next(request)
        process_time = time.time() - start_time

        log_level = "error" if response.status_code >= 400 else "info"
        getattr(logger, log_level)(
            f"[{request_id}] Response: {response.status_code} | Time: {process_time:.4f}s"
        )

        return response

    except Exception as e:
        process_time = time.time() - start_time
        logger.error(f"[{request_id}] Failed after {process_time:.4f}s | Error: {str(e)}")
        raise
